### ISSUE TITLE
Failing optionalParams check (register)

### ISSUE THREAD

**Issue by mars** [linitix/nzero-push#22]
When calling #register with two parameters (the token & a callback,) the conditional logic fails for `optionalParams` because it's a function:

    Undefined optional parameter Error: Undefined optional parameter
    at ZeroPush.register (node_modules/nzero-push/lib/zero_push.js:270:21)

**Comment by igorissen** [comment]
Hi @mars

Which version of the module do you use ?

**Comment by mars** [comment]
Encountered using the newest, 1.3.2.

Also tried with 1.3.1 which throws a slightly different error:

    undefined is not a function TypeError: undefined is not a function
    at ZeroPush.register (node_modules/nzero-push/lib/zero_push.js:264:12)

Here's my ES6 code that's throwing; [two-argument usage per the docs](https://github.com/linitix/nzero-push/wiki/register#only-a-device-token):

    (deviceToken) => {
      return new Promise((resolve, reject) => {
        zeroPush.register(deviceToken, (error, response) => {
          if (error) {
            reject(error);
          } else {
            resolve(response);
          }
        })
      });
    };

**Comment by mars** [comment]
Found a workaround: pass an empty array for the second argument `optionalParams`.

**Comment by igorissen** [comment]
Can you use this command to retrieve the latest modification I have made and test your code please.

```
$ npm install --save git+https://github.com/linitix/nzero-push.git#develop
```

**Comment by mars** [comment]
Thanks for the notification, but cannot test it.

We dropped this module & wrote our own ZeroPush REST API adapter for the calls we needed.
