### ISSUE TITLE
Android 'notify' not working

### ISSUE THREAD

**Issue by bandraszyk** [linitix/nzero-push#24]
Hi,

I saw that in v1.2.0 you have added the support for Android in 'notify' method. But this code is simply not there so in the latest version I'm not able to notify android device. Instead of successful notification I have this: "Unknown platform type! Please chose between ios-mac or safari!". Is there any possibility we can release the new version soon with this commit included https://github.com/linitix/nzero-push/commit/c365816a8c69138e1204447ec85d428924c78b0d?

Thanks in advance!

P.S. I need this like asap, like now, like 10 minutes ago ;)

**Comment by igorissen** [comment]
Sorry for the delay. Can you try the latest [version](https://github.com/linitix/nzero-push/wiki/notify) ? `npm install [--save] nzero-push@latest`

**Comment by bandraszyk** [comment]
You probably fix this one, but I'm not able to test it, because you made a mistake in last commit: https://github.com/linitix/nzero-push/commit/db3742a0f7014cb5e2ab7c345259d60310fe8e56 . Basically, you forgot to change a file name from /lib/schames/device_token_schema.json to /lib/schames/device_tokens_schema.json (so 'token' -> 'tokens') so code is not working (at least notify method) from v2.0.0

**Comment by igorissen** [comment]
v2.1.1 published on npmjs.

Thanks for your help!

**Comment by bandraszyk** [comment]
All is fine now! I'm closing the issue. Many thanks for your effort!

**Comment by igorissen** [comment]
Thanks for your patient.
